sonar.projectKey=lfleury78_Projet_Devops2
sonar.organization=lfleury78
sonar.projectName=Projet_Devops
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8
